version: '3.8'

services:
  jupyter-oracle:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - DB_USER=your_username
      - DB_PASSWORD=your_password
      - DB_DSN=host:1521/service_name
    restart: unless-stopped
